/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import Codigo.Conexion;
import java.sql.Connection;
import java.sql.*;
import Interfaz.MenuPrincipal;
/**
 *
 * @author Usuario
 */
public class RegistroDocentes extends javax.swing.JFrame {
    DefaultTableModel modelo;
    String[] titulos = {"ID", "Nombre", "A.paterno", "A.materno", "Edad", "Genero", "Direccion"};
    String[] datos = new String[7];                                           
    Conexion mysql = new Conexion();
    Connection cn = mysql.establecerConexion();
    MenuPrincipal men;
    /**
     * Creates new form RegistroDocentes
     */
    public RegistroDocentes(MenuPrincipal men) {
        this.men = men;
        initComponents();
        this.setLocationRelativeTo(null);
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        txtnom = new javax.swing.JTextField();
        txtapellpat = new javax.swing.JTextField();
        txtapellmat = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cbxedad = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cbxgenero = new javax.swing.JComboBox<>();
        txtdir = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnlimpiar = new javax.swing.JButton();
        btnguardar = new javax.swing.JButton();
        btnsalir = new javax.swing.JButton();
        pan = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel5.setText("Id:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, 30));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel3.setText("Nombre:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, 30));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel4.setText("Apellido Paterno:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, 30));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel6.setText("Apellido Materno:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, 30));

        txtid.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        txtid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidActionPerformed(evt);
            }
        });
        getContentPane().add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 110, 30));

        txtnom.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        txtnom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnomActionPerformed(evt);
            }
        });
        getContentPane().add(txtnom, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 110, 30));

        txtapellpat.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        txtapellpat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtapellpatActionPerformed(evt);
            }
        });
        getContentPane().add(txtapellpat, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 110, 30));

        txtapellmat.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        txtapellmat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtapellmatActionPerformed(evt);
            }
        });
        getContentPane().add(txtapellmat, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 110, 30));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel7.setText("Edad:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, -1, 30));

        cbxedad.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        cbxedad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "....", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40" }));
        getContentPane().add(cbxedad, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 70, 60, 30));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel8.setText("Genero:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, -1, 30));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel9.setText("Direccion:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, -1, 30));

        cbxgenero.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        cbxgenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "....", "M", "F" }));
        cbxgenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxgeneroActionPerformed(evt);
            }
        });
        getContentPane().add(cbxgenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 110, 60, 30));

        txtdir.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        txtdir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdirActionPerformed(evt);
            }
        });
        getContentPane().add(txtdir, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 110, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Insertar docente");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        btnlimpiar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnlimpiar.setText("Volver");
        btnlimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(btnlimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, -1, -1));

        btnguardar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnguardar.setText("Guardar");
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnguardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 260, -1, -1));

        btnsalir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnsalir.setText("Salir");
        btnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnsalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 260, -1, -1));
        getContentPane().add(pan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 559, 310));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidActionPerformed

    private void txtnomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnomActionPerformed

    private void txtapellpatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtapellpatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtapellpatActionPerformed

    private void cbxgeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxgeneroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxgeneroActionPerformed

    private void txtdirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdirActionPerformed

    private void btnlimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlimpiarActionPerformed
        men.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnlimpiarActionPerformed

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed
        String id, nom, apellpat, apellmat, genero, dir = "";
        int edad = 0;
        String sSQL = "";
        id = txtid.getText();
        nom = txtnom.getText();
        apellpat = txtapellpat.getText();
        apellmat = txtapellmat.getText();
        dir = txtdir.getText();
        genero = cbxgenero.getSelectedItem().toString();
        edad = Integer.parseInt(cbxedad.getSelectedItem().toString());
        sSQL = "INSERT INTO Docente (id, nombre, apellidopaterno, apellidomaterno, edad, genero, direccion) VALUES (?, ?, ?, ?, ?, ?, ?)";

        try {
            PreparedStatement pst = cn.prepareStatement(sSQL);
            pst.setString(1, id);
            pst.setString(2, nom);
            pst.setString(3, apellpat);
            pst.setString(4, apellmat);
            pst.setInt(5, edad);
            pst.setString(6, genero);
            pst.setString(7, dir);

            pst.executeUpdate(); // Ejecutar la inserción
            pst.close(); // Cerrar el PreparedStatement
            JOptionPane.showMessageDialog(null, "Se registro con exito al docente");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error" + ex, "Ingreso", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnguardarActionPerformed

    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed
        System.exit(0);// TODO add your handling code here:
    }//GEN-LAST:event_btnsalirActionPerformed

    private void txtapellmatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtapellmatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtapellmatActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(RegistroDocentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(RegistroDocentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(RegistroDocentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(RegistroDocentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new RegistroDocentes().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnguardar;
    private javax.swing.JButton btnlimpiar;
    private javax.swing.JButton btnsalir;
    private javax.swing.JComboBox<String> cbxedad;
    private javax.swing.JComboBox<String> cbxgenero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel pan;
    private javax.swing.JTextField txtapellmat;
    private javax.swing.JTextField txtapellpat;
    private javax.swing.JTextField txtdir;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtnom;
    // End of variables declaration//GEN-END:variables
}
