/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;
import Codigo.Conexion;
import java.sql.CallableStatement;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
/**
 *
 * @author Usuario
 */
public class Validacion extends javax.swing.JFrame {
    Conexion objetoCon = new Conexion();
    Connection conectar = objetoCon.establecerConexion();
    /**
     * Creates new form Validacion
     */
    public Validacion() {
        this.setLocationRelativeTo(null);
        initComponents();
    }
    public int existeParque(String nom, String val){
        PreparedStatement a = null;
        ResultSet b = null;
        String sql = "SELECT count(idParque)FROM Parque where nombre = ? and valor = ?";
        try{
            a = conectar.prepareStatement(sql);
            a.setString(1,nom);
            a.setString(2,val);
            b = a.executeQuery();
            if(b.next()){
                return b.getInt(1);
            }
            return 1;
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, "error: " + e.toString());
            return 1;
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        camp1 = new javax.swing.JLabel();
        camp2 = new javax.swing.JLabel();
        nomPark = new javax.swing.JTextField();
        valPark = new javax.swing.JTextField();
        in = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titulo.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        titulo.setText("LISTA DE PARQUES");

        camp1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        camp1.setText("NOMBRE DEL PARQUE :");

        camp2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        camp2.setText("VALOR :");

        nomPark.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomParkActionPerformed(evt);
            }
        });

        valPark.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valParkActionPerformed(evt);
            }
        });

        in.setFont(new java.awt.Font("DialogInput", 1, 12)); // NOI18N
        in.setText("Ingresar");
        in.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(titulo))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(camp1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(camp2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(49, 49, 49)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nomPark)
                            .addComponent(valPark, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(222, 222, 222)
                        .addComponent(in, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(titulo)
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(camp1)
                    .addComponent(nomPark, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(camp2)
                    .addComponent(valPark, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addComponent(in)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nomParkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomParkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomParkActionPerformed

    private void inActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inActionPerformed
        String nombrePark = nomPark.getText();
        String valorPark = valPark.getText();
        int valorInt = Integer.valueOf(valorPark);
        if(nombrePark.equals("") || valorPark.equals("")){
            JOptionPane.showMessageDialog(null, "Se detectatron campos vacios, debe llenar par completar la acción");
        }else{
            if(this.existeParque(nombrePark,valorPark) == 0){
                try{
                    CallableStatement c = conectar.prepareCall("{call añadirParque(?,?)}");
                    c.setString(1,nombrePark);
                    c.setInt(2,valorInt);
                    c.execute();
                    c.close();
                    JOptionPane.showMessageDialog(null, "Se añadio con exito el parque");
                } catch(Exception e){
                    JOptionPane.showMessageDialog(null, "error: " + e.toString());
                }
            }else{
                JOptionPane.showMessageDialog(null, "El parque que desea ingresar ya existe");
            }
                }
    }//GEN-LAST:event_inActionPerformed

    private void valParkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valParkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valParkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Validacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Validacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Validacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Validacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Validacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel camp1;
    private javax.swing.JLabel camp2;
    private javax.swing.JButton in;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nomPark;
    private javax.swing.JLabel titulo;
    private javax.swing.JTextField valPark;
    // End of variables declaration//GEN-END:variables
}
